Makefile
annactl/error.go
annactl/main.go
annactl/read_plain.go
api/api.go
client/encoder_decoder.go
client/endpoint.go
client/error.go
client/text_interface.go
neuron/character.go
server/interface/text/encoder_decoder.go
server/interface/text/endpoint.go
server/interface/text/handlers.go
server/interface/text/request_response.go
server/interface/text/text_interface.go
server/server.go
server/spec/text_interface.go

With this I want to provide a basic client that talks to Annas API. For convenience and ease the two step API calls `annactl` provides a way to let Anna read plain text in this first version.
```
annactl readplain this is arbitrary input Anna reads
```

wrote basic client

---

annactl/main.go
annactl/read_plain.go
client/error.go
client/text_interface.go
client/text_interface_test.go

client tests

---

core/core.go
doc/diary/2016_01_27.md
doc/diary/2016_02_01.md
doc/diary/2016_02_04.md
doc/diary/README.md
doc/diary/structure.md
factory/client/client.go
factory/server/server.go
factory/server/server_test.go
file-system/fake/error.go
file-system/fake/fake.go
file-system/file_system.go
file-system/real/error.go
file-system/real/real.go
impulse/impulse.go
main.go
network/network.go
neuron/character.go
neuron/first.go
neuron/job.go
spec/file_system.go
state/json_unmarshal.go
state/reader.go
state/state.go
state/state_test.go
state/writer.go

fixes https://github.com/xh3b4sd/anna/issues/14

mock file system

---

Makefile
doc/development/README.md

This aims to get the project structure right. Problem is that `go test ./... -cover` does not show any coverage results.

fixed gopath

---

.gitignore
.travis.yml
Makefile
README.md
go.test.sh

Make codecov integration work.

Codecov bash uploader

---

Makefile
anna.go
annactl/annactl.go
annactl/control.go
annactl/control_log.go
annactl/control_log_reset.go
annactl/control_log_reset_levels.go
annactl/control_log_reset_objects.go
annactl/control_log_reset_verbosity.go
annactl/control_log_set.go
annactl/control_log_set_levels.go
annactl/control_log_set_objects.go
annactl/control_log_set_verbosity.go
annactl/interface.go
annactl/interface_text.go
annactl/interface_text_read.go
annactl/interface_text_read_plain.go
annactl/version.go
completion/zsh/_anna
completion/zsh/_annactl
doc/concept/anna.md
doc/concept/annactl.md
factory/client/client_test.go
factory/server/server_test.go
gateway/signal_test.go
spec/state.go
state/reader.go
state/state.go
state/state_test.go
version.go

fixes #31 
fixes #33 
fixes #39

add version commands and add version to state

---

README.md

customized badges

---

client/control/log/error.go
client/control/log/error_test.go
client/control/log/log_control.go
client/control/log/log_control_test.go
client/interface/text/error.go
client/interface/text/error_test.go
client/interface/text/text_interface.go
client/interface/text/text_interface_test.go
factory/server/error.go
factory/server/error_test.go
log/error.go
log/error_test.go

Some improvements for error handling.

better error handling

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
README.md
doc/development/README.md

pr templates

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
README.md
api/api.go
client/control/log/log_control.go
client/control/log/log_control_test.go
client/interface/text/text_interface.go
client/interface/text/text_interface_test.go
common/gateway.go
factory/server/server_test.go
gateway/signal_test.go
log/log_test.go
state/common.go
state/error.go
state/json_marshal.go
state/json_unmarshal.go
state/state_test.go

This is to refactor the state unmarshalling for cleaner code and more structure.
fixes #57

refactor state unmarshaling

---

doc/evaluation/pattern_recognition.md

More patterns

---

anna.go
annactl/annactl.go
completion/zsh/_anna
server/server.go

renamed host to addr

---

anna.go
core/core.go

See #64, #65
fixes #64 
fixes #65

properly close factory and shutdown in main object

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
doc/diary/2016_03_14.md
doc/diary/2016_03_22.md
doc/evaluation/mind.md
gateway/gateway_test.go
net/pat/common.go
net/pat/distribution.go
net/pat/distribution_object.go
net/pat/distribution_object_test.go
net/pat/distribution_test.go
net/pat/error.go
net/pat/error_test.go
net/pat/feature.go
net/pat/feature_set.go
net/pat/feature_set_test.go
net/pat/feature_test.go
spec/distribution.go
spec/feature.go
spec/feature_set.go
spec/strategy.go
strategy/strategy.go
strategy/strategy_test.go

This goes into the direction of pattern recognition. See the diary, godoc and tests for more information.

create pattern recognition language

---

doc/development/docker.md
doc/development/makefile.md

This goes towards #133.
This fies #133.

added docker related makefile targets to development docs

---

doc/concept/README.md
doc/concept/instrumentation.md

- See #141.
- This fixes #141.

documented instrumentation

---

doc/development/README.md
doc/development/debugging.md

- See #143.
- This fixes #143.

added pprof documentation

---

anna/anna.go
annactl/annactl.go
annactl/control.go
annactl/control_log.go
annactl/control_log_reset.go
annactl/control_log_reset_levels.go
annactl/control_log_reset_objects.go
annactl/control_log_reset_verbosity.go
annactl/control_log_set.go
annactl/control_log_set_levels.go
annactl/control_log_set_objects.go
annactl/control_log_set_verbosity.go
annactl/interface.go
annactl/interface_text.go
annactl/interface_text_read.go
annactl/interface_text_read_file.go
annactl/interface_text_read_plain.go

This fixes breaking changes introduced by spf13/cobra: fixed spf13/cobra breaking changes.

fixed spf13/cobra breaking changes

---

Makefile
clg/is-greater/calculate.go
doc/concept/connection.md
doc/diary/2016_03_07.md
doc/diary/2016_04_14.md
instrumentation/prometheus/histogram.go

This PR goes towards further innovations of the connection space model.

Connection space

---

doc/development/cheat_sheet.md
go.test.sh

This PR improves the test suite and thus code quality. 
This PR fixes #127.

added -race to test suite

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
doc/concept/README.md
doc/concept/clg.md
doc/concept/input.md
doc/concept/state.md
doc/diary/2016_01_11.md
doc/diary/2016_01_18.md
doc/diary/2016_02_01.md
doc/diary/2016_06_23.md
doc/evaluation/starting_a_conversation_by_greeting.md

@mewmew created #180 in which he pointed to some broken references within the projects documentation. Here I tried to fix this issue where possible. Please give me a shout on what you think. 
This PR aims to fix #180.

fixed broken links within documentation

---

LICENSE

@mewmew pointed to some issues with the project license. This is a chance to improve on that. Please give me a shout on what you think about these changes. I decided to go with the BSD license of the golang project. Reading through it, it makes sense to me. Again, I am not that license guy and all these things are more or less nightmares for me. Anyway, I think this PR improves the situation. 
This PR aims to fix #178.

added more proper license

---

README.md

Recently there have been improvements on the project license. See #183. This PR improves the license section in the readme since it was forgotten about in the former pull request.

improved license section

---

annactl/annactl.go
client/interface/text/client.go
project.check.sh
spec/text_interface.go

improved text interface client

---

.travis.yml
doc/concept/connection.md
network/activate.go
network/common.go
network/error.go
network/network.go
spec/network.go

Activate connections

---

doc/concept/connection.md
network/tracker/tracker.go
spec/storage.go

This PR implements tracking of multiple destinations as this is the nature of the connection model.

Destination

---

anna/service_collection.go
annactl/service_collection.go
clg/input/calculate_test.go
service/collection.go
service/fs/fs.go
service/fs/mem/mem.go
service/fs/mem/service.go
service/fs/os/error.go
service/fs/os/object.go
service/fs/os/os.go
service/spec/file_system.go
service/spec/service.go
spec/service.go

renamed FileSystem to FS

---

annactl/service_collection.go
annad/annad.go
annad/main.go
annad/service_collection.go
service/collection.go
service/metricsendpoint/error.go
service/metricsendpoint/service.go
service/spec/collection.go
service/spec/metrics_endpoint.go

This PR renames the server package to metricsendpoint, which is more appropriate considering its current functionality.

renamed server package to metricsendpoint
